# -*- coding: utf-8 -*-
"""passwordGame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oJFUitOKWnyxW5CqmjgQg9WwnTTGo26T
"""

import datetime
import re

times = [
    "AtléticoMineiro","Bahia","Botafogo","Bragantino","Corinthians",
    "Criciúma","Cruzeiro","Cuiabá","Flamengo","Fluminense",
    "Fortaleza","Grêmio","Internacional","Juventude","Palmeiras",
    "SãoPaulo","Vasco","Vitória","AthleticoParanaense","AtléticoGoianiense"
]

print("PASSWORD GAME --- por Fillipe")
print("Seu objetivo no jogo e criar uma senha que esteja dentro das regras\n")
print("Se conseguir criar uma senha você terá uma recompensa")

while True:

    senha = input("\nDigite sua senha: ")

    tamanho = len(senha)
    numeros = re.findall(r'\d+', senha)
    ano = str(datetime.datetime.now().year)

    tem_numero = any(c.isdigit() for c in senha)
    tem_maiuscula = any(c.isupper() for c in senha)
    tem_ano = ano in senha
    tem_nome = "fillipe" in senha.lower()
    tem_emoji = any(e in senha for e in ["↑","☝️","👆","⬆️","🔝","⤴️","🖕"])
    tem_time = any(t.lower() in senha.lower() for t in times)
    tem_romano = "LXIX" in senha
    tem_vingador = "hulk" in senha.lower()

    tem_tamanho = False
    for n in numeros:
        if int(n) == tamanho:
            tem_tamanho = True

    # BLOCO ÚNICO DE CONDIÇÃO
    if not tem_numero:
        print("❌ A senha deve conter um número")

    elif not tem_maiuscula:
        print("❌ A senha deve conter letra maiúscula")

    elif not tem_ano:
        print("❌ A senha deve conter o ano atual")

    elif not tem_nome:
        print("❌ A senha deve conter o nome do criador do jogo")

    elif not tem_emoji:
        print("❌ A senha deve conter um emoji que aponta pra cima")

    elif not tem_time:
        print("❌ A senha deve conter um time do Brasileirão")

    elif not tem_tamanho:
        print("❌ A senha deve conter o número de caracteres da senha")

    elif not tem_romano:
        print("❌ A senha deve conter o número 69 em romano")

    elif not tem_vingador:
        print("❌ A senha deve conter o nome do vingador mais forte (jogador mais fraco)")

    else:
        print("\nParabéns! Você venceu o jogo!")
        print("Recompensa: https://r.mtdv.me/videos/DoF3K5rNSK")
        break